export const FAKE_GAMES = [
  {
    id: 842,
    score: 169.4362506866455,
    document: {
      id: 45036,
      cover: {
        id: 112684,
        alpha_channel: false,
        animated: false,
        game: 45036,
        height: 972,
        image_id: "co2ey4",
        url: "https://images.igdb.com/igdb/image/upload/t_1080p/co2ey4.jpg",
        width: 729,
        checksum: "badc6232-7a24-2a81-a139-15416015f3c3",
      },
      first_release_date: 975110400,
      genres: [
        {
          id: 5,
          name: "Shooter",
        },
      ],
      name: "RayCrisis: Series Termination",
      slug: "raycrisis-series-termination",
      summary:
        "An ambitious and unethical scientist, a secret experiment gone horribly awry, and an artificially intelligent supercomputer gone mad; all the necessary ingredients for the imminent extinction of mankind. You are humanity's last hope, a hotshot pilot given the unenviable task of flying an experimental fighter into the dark heart of the Con-Human Network. Seize the controls of three Wave Rider spacecraft, each equippped with the WR-01 primary weapon array, WR-02 secondary lock-on laser system, and WR-03 single-use weapon for emergency situations. RayCrisis: Series Termination is the final entry in Taito's acclaimed trilogy of shooters, and it bombards your CRT with an abundance of fourth-generation optical stimulation: multilevel scrolling, transparency and lighting effects, and enough polygons to overload your cerebral cortex. Dodge, weave, and blast through two play modes, disintegrating wave after wave of relentless bogeys, to achieve high scores and unlock hidden bonuses. Prepare your senses, reinforce your nerves, and limber your trigger finger - the final assault has begun!",
      url: "https://www.igdb.com/games/raycrisis-series-termination",
    },
  },
  {
    id: 222,
    score: 167.93079376220703,
    document: {
      id: 28055,
      alternative_names: [
        {
          id: 8361,
          name: "カウントダウンヴァンパイアーズ",
        },
      ],
      cover: {
        id: 133613,
        alpha_channel: false,
        animated: false,
        game: 28055,
        height: 864,
        image_id: "co2v3h",
        url: "https://images.igdb.com/igdb/image/upload/t_1080p/co2v3h.jpg",
        width: 648,
        checksum: "057a57e2-437a-bcbf-6101-a2c220598679",
      },
      first_release_date: 945820800,
      genres: [
        {
          id: 31,
          name: "Adventure",
        },
      ],
      involved_companies: [
        {
          id: 45735,
          company: {
            id: 2325,
            name: "K2 LLC",
          },
          created_at: 1491264000,
          developer: true,
          game: 28055,
          porting: false,
          publisher: false,
          supporting: false,
          updated_at: 1491264000,
          checksum: "8c098710-26a8-047e-1fc5-b45f22d98e8c",
        },
        {
          id: 45736,
          company: {
            id: 617,
            name: "Bandai",
          },
          created_at: 1491264000,
          developer: false,
          game: 28055,
          porting: false,
          publisher: true,
          supporting: false,
          updated_at: 1491264000,
          checksum: "284f7f72-db7d-41a5-7974-ace37074f134",
        },
      ],
      name: "Countdown Vampires",
      screenshots: [
        {
          id: 426353,
          alpha_channel: false,
          animated: false,
          game: 28055,
          height: 900,
          image_id: "sc94z5",
          url: "https://images.igdb.com/igdb/image/upload/t_1080p/sc94z5.jpg",
          width: 1600,
          checksum: "45643c01-196c-665a-f74f-bdf78f7be102",
        },
      ],
      slug: "countdown-vampires",
      summary:
        "Because Capcom's Resident Evil single-handedly created the modern survival horror genre, the critically acclaimed adventure spawned countless sequels and clones. Conceived by Bandai Digital Entertainment, Countdown Vampires is one of those clones -- you will maneuver 3D characters throughout 2D backgrounds in a series of fixed camera angles while fending off unspeakable horrors. \n \nAs a police officer, Keith J. Snyder has been assigned a security position at the grand opening of Desert Moon -- a hotel casino with a horror theme located in Casino City. While overseeing security and making sure VIPs aren't being hurt at the dance club, something goes horribly wrong. As a sudden fire causes sprinklers to go off, the water turns black and transforms the dancers into murderous vampire monsters. Assuming the role of the brave police detective, a civic servant and the last remaining human alive, Snyder must unravel the mysteries of the black water while defending himself against multiple monstrosities. \n \nArmed initially with a tranquilizer gun, a shock glove and an unlimited supply of vampire-destroying white water, Keith J. Snyder will find and utilize twelve weapons and items throughout the course of his adventure. Also located throughout the hotel casino are computer terminals, maps of the area and vending machines in which helpful items are sold; at computer terminals, he can access an e-mail program that furthers the storyline. \n \nIn Countdown Vampires, Snyder's physical health is represented by a color-based condition gauge found in the inventory screen; green indicates a healthy body, yellow represents wounded and red coloring is fatal as Snyder approaches death. You can heal the character using various health items found throughout the casino. In addition to looking out for your character's health, you will solve various puzzles and seek out specific keys and cards for locked doors.",
      url: "https://www.igdb.com/games/countdown-vampires",
    },
  },
  {
    id: 636,
    score: 164.88266277313232,
    document: {
      id: 44788,
      alternative_names: [
        {
          id: 14620,
          name: "Mr. Driller Great",
        },
        {
          id: 45953,
          name: "Mr. Driller Great",
        },
      ],
      collection: {
        id: 2305,
        created_at: 1469304561,
        games: [
          4021, 18330, 21356, 21840, 25176, 44788, 49260, 50991, 92644, 135546,
        ],
        name: "Mr. Driller",
        slug: "mr-driller",
        updated_at: 1667839290,
        url: "https://www.igdb.com/collections/mr-driller",
        checksum: "96031921-575f-5e72-ef0e-6800ee357688",
      },
      cover: {
        id: 56426,
        game: 44788,
        height: 512,
        image_id: "qbios6kb700x2kpkjbzm",
        url: "https://images.igdb.com/igdb/image/upload/t_1080p/qbios6kb700x2kpkjbzm.jpg",
        width: 512,
        checksum: "832b2aab-dc8c-3d8f-ebfb-2dc35c3465cf",
      },
      first_release_date: 1008979200,
      genres: [
        {
          id: 9,
          name: "Puzzle",
        },
      ],
      name: "Mr. Driller G",
      slug: "mr-driller-g",
      summary:
        "A.D 2000X in Tokyo, a mysterious occurrence of overflowing Blocks was halted by the actions of a Professional Excavator \"Driller\" by the name of SusumuHori. Above ground, peace returned again.\n\nHalf a year passed, suddenly the Blocks began to overflow in three nations.One after another America, India and Egypt became flooded in blocks.\n\nSusumu Hori and his Rival Driller, Anna Hottenmeyer; urgently began to dig to the depths of the earth. Meanwhile, Susumu's father, Taizou Hori; Susumu'selder brother, Ataru Hori; Anna's Robot Assistant, Horinger Z and Susumu's roomate, Puchi, were all digging to the depths of the earth, aiming for the resolution of this disaster.\n\nWhat is the probable cause of this latest incident?\nAnd, among the 6 Drillers, who will be the one to resolve this disaster?\n\nOur hero can drill up, down, left and right. Drilling through single blocks would take forever, so it's fortunate that blocks of the same color form into groups that vanish when only one of the blocks is drilled. This allows for chain reactions, since vanishing blocks will often cause other blocks to fall and form new groups. Alas, these falling blocks are also deadly if they hit Mr. Driller.\n\nIf all Mr. Driller had to do was drill, life would be easy. But he also has to keep refilling his oxygen supply by collecting air capsules scattered throughout the blocks. The deeper he goes, the faster his air runs out. Hampering his progress even further are brown \"X-blocks\" that take five drill strikes to disappear and remove 20% of Mr. Driller's air when broken.\n\nThis game is a Japan-only port of the original Arcade game of the same name.",
      url: "https://www.igdb.com/games/mr-driller-g",
    },
  },
  {
    id: 956,
    score: 163.22746658325195,
    document: {
      id: 9347,
      collection: {
        id: 1094,
        created_at: 1416256662,
        games: [1377, 9340, 9341, 9342, 9343, 9344, 9345, 9346, 9347, 80887],
        name: "Spec Ops",
        slug: "spec-ops",
        updated_at: 1667579161,
        url: "https://www.igdb.com/collections/spec-ops",
        checksum: "5b24ba09-30b8-94c2-f6cf-2055fae8c781",
      },
      cover: {
        id: 161275,
        alpha_channel: false,
        animated: false,
        game: 9347,
        height: 568,
        image_id: "co3gfv",
        url: "https://images.igdb.com/igdb/image/upload/t_1080p/co3gfv.jpg",
        width: 426,
        checksum: "e4b69b70-c8ee-bb9f-40b4-2d25563697e9",
      },
      first_release_date: 1036022400,
      genres: [
        {
          id: 5,
          name: "Shooter",
        },
        {
          id: 15,
          name: "Strategy",
        },
        {
          id: 24,
          name: "Tactical",
        },
      ],
      involved_companies: [
        {
          id: 22673,
          company: {
            id: 5074,
            name: "Big Grub",
          },
          created_at: 1427846400,
          developer: true,
          game: 9347,
          porting: false,
          publisher: false,
          supporting: false,
          updated_at: 1427932800,
          checksum: "fa759950-3a3c-2dbd-50bd-6076f2c31b71",
        },
        {
          id: 22674,
          company: {
            id: 139,
            name: "Take-Two Interactive",
          },
          created_at: 1427846400,
          developer: false,
          game: 9347,
          porting: false,
          publisher: true,
          supporting: false,
          updated_at: 1427932800,
          checksum: "49a48cb2-9d98-0d5b-e704-a68f392c5cf5",
        },
        {
          id: 22675,
          company: {
            id: 1936,
            name: "Gotham Games",
          },
          created_at: 1427846400,
          developer: false,
          game: 9347,
          porting: false,
          publisher: true,
          supporting: false,
          updated_at: 1427932800,
          checksum: "ecb4b1d4-a0f2-0c87-adec-694dd71345a3",
        },
        {
          id: 22676,
          company: {
            id: 45,
            name: "Sony Computer Entertainment, Inc. (SCEI)",
          },
          created_at: 1427846400,
          developer: false,
          game: 9347,
          porting: false,
          publisher: true,
          supporting: false,
          updated_at: 1427932800,
          checksum: "8a7d6049-c607-686d-77e2-47ce9e63e624",
        },
      ],
      name: "Spec Ops: Airborne Commando",
      slug: "spec-ops-airborne-commando",
      summary:
        "The first Spec Ops title on the PlayStation to feature a third-person 3D shooting style, Spec Ops: Airborne Commando literally drops you behind enemy lines as an elite U. S. Ranger paratrooper equipped with essential gear and a lethal arsenal. Weapons include a standard military knife, a Colt 1911A1 Semiautomatic pistol, silenced M4 rifle, sniper rifle (Barret M82A1), the M3 RAAW reusable launcher rifle, hand grenades, and C4 demolition packs. Binoculars, a laptop, and a handheld radio round out the inventory, with satellite imaging available for locating positions of rangers, checkpoints, helicopter extractions, and both real and decoy SAM launchers.\n\nPlayers earn awards and promotions for successfully completing the 16 missions, with scores based on factors such as reconnaissance and intelligence recovered, rescue of hostages, enemies killed, and demolition. Ten ranks can be achieved, ranging from Private E1 to Sergeant Major and, depending on success, six decorations and medals can be earned, including The Purple Heart, Bronze or Silver Stars and the Congressional Medal of Honor. Airborne Commando features five difficulty settings, ranging from Super Easy (10 extra lives) to Super Hard (no extra lives).",
      url: "https://www.igdb.com/games/spec-ops-airborne-commando",
    },
  },
  {
    id: 748,
    score: 162.836332321167,
    document: {
      id: 1000,
      alternative_names: [
        {
          id: 30023,
          name: "Oddworld : L'Exode d'Abe",
        },
        {
          id: 71903,
          name: "Abe'99",
        },
        {
          id: 71904,
          name: "Abe's Exoddus",
        },
      ],
      collection: {
        id: 223,
        created_at: 1322574238,
        games: [
          999, 1000, 1001, 1002, 5552, 18357, 21070, 49015, 49865, 51329, 65861,
          66007, 118466, 121444, 134025, 146008, 146118, 178211,
        ],
        name: "Oddworld",
        slug: "oddworld",
        updated_at: 1668482507,
        url: "https://www.igdb.com/collections/oddworld",
        checksum: "4a88666f-5c41-9c5c-618b-823e4ead2712",
      },
      cover: {
        id: 173511,
        alpha_channel: false,
        animated: false,
        game: 1000,
        height: 957,
        image_id: "co3pvr",
        url: "https://images.igdb.com/igdb/image/upload/t_1080p/co3pvr.jpg",
        width: 718,
        checksum: "7446172d-a327-9425-abc2-69089c89a1d9",
      },
      first_release_date: 911260800,
      genres: [
        {
          id: 8,
          name: "Platform",
        },
        {
          id: 9,
          name: "Puzzle",
        },
        {
          id: 31,
          name: "Adventure",
        },
      ],
      involved_companies: [
        {
          id: 178231,
          company: {
            id: 727,
            name: "Oddworld Inhabitants",
          },
          created_at: 1657319236,
          developer: true,
          game: 1000,
          porting: false,
          publisher: false,
          supporting: false,
          updated_at: 1657438947,
          checksum: "e37edbcb-b1d2-6d0f-20bc-e50d33ded2a4",
        },
        {
          id: 178232,
          company: {
            id: 205,
            name: "GT Interactive",
          },
          created_at: 1657319236,
          developer: false,
          game: 1000,
          porting: false,
          publisher: true,
          supporting: false,
          updated_at: 1657438947,
          checksum: "96b2e7ef-57a9-8f5c-1851-cceff5c0c258",
        },
        {
          id: 178234,
          company: {
            id: 727,
            name: "Oddworld Inhabitants",
          },
          created_at: 1657319236,
          developer: false,
          game: 1000,
          porting: false,
          publisher: true,
          supporting: false,
          updated_at: 1657438947,
          checksum: "3d8a7cfc-a740-5e09-28a0-01c6ec7d2532",
        },
        {
          id: 178257,
          company: {
            id: 311,
            name: "Digital Dialect",
          },
          created_at: 1657361131,
          developer: false,
          game: 1000,
          porting: true,
          publisher: false,
          supporting: false,
          updated_at: 1657438947,
          checksum: "fd14a3d2-e039-a02a-1aed-6f4c48f9c218",
        },
      ],
      name: "Oddworld: Abe's Exoddus",
      screenshots: [
        {
          id: 831844,
          alpha_channel: false,
          animated: false,
          game: 1000,
          height: 480,
          image_id: "schtus",
          url: "https://images.igdb.com/igdb/image/upload/t_1080p/schtus.jpg",
          width: 640,
          checksum: "70f195a6-d704-4872-0161-fe9b114f11b7",
        },
        {
          id: 831845,
          alpha_channel: false,
          animated: false,
          game: 1000,
          height: 480,
          image_id: "schtut",
          url: "https://images.igdb.com/igdb/image/upload/t_1080p/schtut.jpg",
          width: 640,
          checksum: "d46bccb2-7e6b-f66f-6809-09f3c3cbd0a3",
        },
        {
          id: 831846,
          alpha_channel: false,
          animated: false,
          game: 1000,
          height: 480,
          image_id: "schtuu",
          url: "https://images.igdb.com/igdb/image/upload/t_1080p/schtuu.jpg",
          width: 640,
          checksum: "b27fa80f-b6bb-3b90-58fa-6cc5e75def91",
        },
        {
          id: 831847,
          alpha_channel: false,
          animated: false,
          game: 1000,
          height: 480,
          image_id: "schtuv",
          url: "https://images.igdb.com/igdb/image/upload/t_1080p/schtuv.jpg",
          width: 640,
          checksum: "a4c625d8-6a51-c71b-b464-fbefd4b9f2e6",
        },
        {
          id: 831848,
          alpha_channel: false,
          animated: false,
          game: 1000,
          height: 480,
          image_id: "schtuw",
          url: "https://images.igdb.com/igdb/image/upload/t_1080p/schtuw.jpg",
          width: 640,
          checksum: "6bfb5f86-4908-b909-0f58-39a4e02c6921",
        },
        {
          id: 831849,
          alpha_channel: false,
          animated: false,
          game: 1000,
          height: 480,
          image_id: "schtux",
          url: "https://images.igdb.com/igdb/image/upload/t_1080p/schtux.jpg",
          width: 640,
          checksum: "2d43ffe5-3b23-e5ef-fc2c-01b6efe342d5",
        },
      ],
      slug: "oddworld-abe-s-exoddus",
      storyline:
        "The game continues the story of Abe, charting his efforts to save his fellow Mudokons from another plot by the Glukkons to exploit them. Abe discovers that the Glukkons are enslaving Mudokons, this time to produce a drink called Soulstorm Brew, which uses Mudokon bones and tears as its ingredients. Abe must travel to the Soul Storm Brewery, stop those corporate villains and save the enslaved Mudokon workers.",
      summary:
        "Abe’s peaceful retirement was shattered when visited by a vision from the Three Weirdos. Abe learned the Magog Cartel was mining Necrum, the sacred Mudokon city of the dead, to collect bones to make super-addictive SoulStorm Brew.\n\nAfter freeing the Mudokon spirits imprisoned in the Mudanchee and Mudomo Vaults, Abe gained scary powers from the Weirdos, including the ability to heal his Mudokon friends of SoulStorm addiction, and the power to turn invisible. Infiltrating the transportation hub of FeeCo Depot, and using explosive farts to survive adventures at the Slig Barracks and Bonewerks, Abe broke into SoulStorm Brewery.\n\nThere Abe learned the truth behind the secret ingredient of SoulStorm Brew... just before blasting the place to atoms with the combined power of the sobered-up Mudokon he’d rescued. Then Abe joined his brew-addled pals at Alf’s Rehab & Tea to take the cure – the journey of a lifetime starts with one step.\n\nOr is it twelve?",
      total_rating: 81.58184769831995,
      total_rating_count: 79,
      url: "https://www.igdb.com/games/oddworld-abe-s-exoddus",
      videos: [
        {
          id: 71611,
          game: 1000,
          name: "Trailer",
          video_id: "eEx8lxXCsU4",
          checksum: "875754dd-ea20-d0d9-61cf-f2433f93f07c",
        },
        {
          id: 71612,
          game: 1000,
          name: "Gameplay Video",
          video_id: "O0THVeTNoxk",
          checksum: "a5b73492-701c-7f71-9a4e-59dd0c45bd2d",
        },
      ],
    },
  },
  {
    id: 50,
    score: 160.83221673965454,
    document: {
      id: 43924,
      cover: {
        id: 196430,
        alpha_channel: true,
        animated: false,
        game: 43924,
        height: 800,
        image_id: "co47ke",
        url: "https://images.igdb.com/igdb/image/upload/t_1080p/co47ke.jpg",
        width: 600,
        checksum: "69cff100-c89c-4e39-16db-e8bba6de3afd",
      },
      first_release_date: 878342400,
      name: "Arcade's Greatest Hits: The Midway Collection 2",
      slug: "arcades-greatest-hits-the-midway-collection-2",
      summary:
        "BLASTER pits your starship shooting skills against endless waves of enemies: Roto-Shooting Robots, Runaway Spaceships, Evasive Vampire Ships, Squads of Saucer Ships, The Masterminds and more - 20 million light years away!\n\nSpecialty of the House! Help Chef Peter Pepper in a race to collect patties, cheese, lettuce and buns! Face challenging mazes, make mounds of burgers and score big time inBURGERTIME!\n\nJOUST 2 the sequel to the record-setting video game, pits you against Buzzards and Vultures in an intense battle for survival. Buzzard eggs hatch into Evil Aggressors while Golden Eggs offer the promise of special rewards and ultimate victory!\n\nAlien attacks, bottomless craters, boulders, land mines, cannons, low-flying planes on your tail and the clock ticking away...These are just some of the challenges awaiting you in MOON PATROL!\n\nIt's fun, refreshing, mug slidin' fun. You'll love serving frosty root beers to the thirsty customers in four different scenes. Quench your thirst for fun with another classic,ROOT BEER TAPPER!\n\nSPLAT, the never-before-seen lost classic! Splat goofy nerds in the face and watch them bounce off the walls. Pass through the door by catching keys and reach the other side with ease. Your enemies are nasty, so beware of speedy hit men, banana peels and popcorn stalkers!\n\nSmoke Screens, Oil Slicks, Missiles, and the guts to use 'em. SPY HUNTER puts you in the seat of your very own high-tech, high performance spy roadster! Avoid the civilian cars while running the bad guys off the road in a ball of fire!",
      url: "https://www.igdb.com/games/arcades-greatest-hits-the-midway-collection-2",
    },
  },
  {
    id: 71,
    score: 158.5324740409851,
    document: {
      id: 43923,
      cover: {
        id: 237722,
        alpha_channel: false,
        animated: false,
        game: 43923,
        height: 800,
        image_id: "co53fe",
        url: "https://images.igdb.com/igdb/image/upload/t_1080p/co53fe.jpg",
        width: 600,
        checksum: "ab60c36e-6b81-3c44-34e5-99a8b5b6c65e",
      },
      first_release_date: 980985600,
      name: "Atari Anniversary Edition Redux",
      slug: "atari-anniversary-edition-redux",
      summary:
        'This collection honors the 30th anniversary of Atari, one of the first great companies in the videogame industry by reissuing versions of 12 arcade classics for play on PlayStation systems. Included are Asteroids and Asteroids Deluxe, Battlezone, Black Widow, Centipede, Gravitar, Missile Command, Pong, Space Duel, Super Breakout, Tempest and Warlords. The bundle also includes a souvenir sticker, a video interview with Atari founder Nolan Bushnell, press releases from the original games and images of game memorabilia. Atari Anniversary Edition Redux is mouse and analog control compatible and is multi-tap adaptable for up to four players.\n\nIn addition to the pure emulation modes, there is an option to display the cabinet art surrounding the display of each game, intended to give the player a sense of actually playing a stand-up machine.\n\nEach game also has a toggle for an "enhanced" graphical mode, which varies from game to game. For instance, "enhanced" asteroids merely has a static backdrop, whereas "enhanced" warlords is a complete graphical overhaul with new colors. It should be noted that the "enhanced" version of Tempest is none other than Tempest Tubes, a modification for Tempest made in 1982 by Duncan Brown.',
      url: "https://www.igdb.com/games/atari-anniversary-edition-redux",
    },
  },
  {
    id: 285,
    score: 157.01353454589844,
    document: {
      id: 8292,
      alternative_names: [
        {
          id: 82408,
          name: "Discworld 2 - Missing Presumed",
        },
        {
          id: 98119,
          name: "Discworld II: Missing Presumed...!?",
        },
      ],
      collection: {
        id: 1115,
        created_at: 1418299230,
        games: [8291, 8292, 8293, 56861],
        name: "Discworld",
        slug: "discworld",
        updated_at: 1660330489,
        url: "https://www.igdb.com/collections/discworld",
        checksum: "745d73c7-6883-231f-8653-62464021a42e",
      },
      cover: {
        id: 126914,
        alpha_channel: false,
        animated: false,
        game: 8292,
        height: 800,
        image_id: "co2pxe",
        url: "https://images.igdb.com/igdb/image/upload/t_1080p/co2pxe.jpg",
        width: 600,
        checksum: "d3683b08-83ee-af39-0cf7-7eb324ade6b4",
      },
      first_release_date: 849312000,
      genres: [
        {
          id: 2,
          name: "Point-and-click",
        },
        {
          id: 31,
          name: "Adventure",
        },
      ],
      involved_companies: [
        {
          id: 20268,
          company: {
            id: 4231,
            name: "Perfect Entertainment",
          },
          created_at: 1418256000,
          developer: true,
          game: 8292,
          porting: false,
          publisher: false,
          supporting: false,
          updated_at: 1418256000,
          checksum: "01ca1d6e-180d-a4ca-a578-2454bd229864",
        },
        {
          id: 20269,
          company: {
            id: 764,
            name: "Psygnosis",
          },
          created_at: 1418256000,
          developer: false,
          game: 8292,
          porting: false,
          publisher: true,
          supporting: false,
          updated_at: 1418256000,
          checksum: "8f34b965-78ac-8574-0669-9e87601c2651",
        },
      ],
      name: "Discworld II: Mortality Bytes!",
      screenshots: [
        {
          id: 7738,
          game: 8292,
          height: 429,
          image_id: "qjdjcf0o7mupnwuadvx1",
          url: "https://images.igdb.com/igdb/image/upload/t_1080p/qjdjcf0o7mupnwuadvx1.jpg",
          width: 640,
          checksum: "35678c44-d4f7-66d9-5253-4008a66c788f",
        },
        {
          id: 7739,
          game: 8292,
          height: 429,
          image_id: "aldy80ibzi65jm90axcu",
          url: "https://images.igdb.com/igdb/image/upload/t_1080p/aldy80ibzi65jm90axcu.jpg",
          width: 639,
          checksum: "f35d20ab-4afa-4841-3ab2-dc281a6508c7",
        },
        {
          id: 7740,
          game: 8292,
          height: 429,
          image_id: "osifnmdk4pxavicdfkql",
          url: "https://images.igdb.com/igdb/image/upload/t_1080p/osifnmdk4pxavicdfkql.jpg",
          width: 639,
          checksum: "9601782c-9604-4be2-c278-1d428b25f910",
        },
        {
          id: 7741,
          game: 8292,
          height: 429,
          image_id: "igsibfwf6i9hcaq2ehei",
          url: "https://images.igdb.com/igdb/image/upload/t_1080p/igsibfwf6i9hcaq2ehei.jpg",
          width: 639,
          checksum: "e3f05526-05b1-bc06-ff08-08c580fd5e77",
        },
      ],
      slug: "discworld-ii-mortality-bytes",
      summary:
        "Discworld II: Mortality Bytes! is the second point-and-click adventure game based on Terry Pratchett's series of fantasy novels set on the mythical Discworld. The game was developed and produced in 1996 by Perfect Entertainment for the PC, and ported in 1997 for the PlayStation and Sega Saturn. It was published by Psygnosis for the PC and PlayStation, and by Sega for the Saturn (only in Europe).\n\nIn Discworld II the player controls Rincewind the \"wizzard\" (voiced by Eric Idle, as in the previous game) who has been burdened with the task of coercing Death out of his impromptu retirement and back into his regular duties. The plot borrows from a number of Discworld books, most notably Reaper Man, Moving Pictures and Lords and Ladies.\n\nIt all begins in a quiet Ankh-Morpork street, where Rincewind and The Librarian inexplicably fail to die from a nearby cart-bomb explosion. The odd event is not shared by them alone however: occurrences of the newly dead re-awakening and disturbing the populace are being reported all over the city, prompting the Archchancellor of Unseen University to halt his usual activities of feasting and merrymaking, and to take charge of the situation. Much to Rincewind's despair, the entirety of this process involves appointing him to the task of finding Death and convincing him to resume his work.",
      total_rating: 90.84718838213129,
      total_rating_count: 24,
      url: "https://www.igdb.com/games/discworld-ii-mortality-bytes",
      videos: [
        {
          id: 73168,
          game: 8292,
          name: "Game Intro",
          video_id: "WfMm4mkyTn4",
          checksum: "98863756-7240-91c7-e3c1-f0bef66a8ce5",
        },
        {
          id: 73169,
          game: 8292,
          name: "Teaser",
          video_id: "lST3b24nVYE",
          checksum: "40d03ce1-1154-2dd4-fdd8-5acd0c7f62c1",
        },
      ],
    },
  },
  {
    id: 409,
    score: 156.64129447937012,
    document: {
      id: 44938,
      cover: {
        id: 205704,
        alpha_channel: true,
        animated: false,
        game: 44938,
        height: 800,
        image_id: "co4eq0",
        url: "https://images.igdb.com/igdb/image/upload/t_1080p/co4eq0.jpg",
        width: 600,
        checksum: "523f9b30-6172-2939-a80f-341723b5ac8d",
      },
      first_release_date: 1041379200,
      genres: [
        {
          id: 5,
          name: "Shooter",
        },
      ],
      name: "Gekioh: Shooting King",
      slug: "gekioh-shooting-king",
      summary:
        "Natsume's vertical scrolling shooter Gekioh: Shooting King offers nine arcade-style modes of nonstop action in a futuristic setting featuring giant mechs, laser-firing, bomb-dropping airships. Environments are filled with power-ups, explosions, and destructive mayhem. Players wield an arsenal consisting of a devastating Vulcan cannon, electrically charged lightning attacks, and missiles capable of decimating ground tanks and flying squadrons. Power-ups include increases in speed, power, shields, bombs, and point bonuses, with the primary weapon changing depending on the last red (cannon), blue (lightning), or yellow (missile) disk picked up.\n\nGekioh: Shooting King features three main levels of difficulty: Geki Mode (normal fire rate), Easy Mode (enemies have half the rate of normal fire and collisions aren't always fatal), and Hard Mode (double firing rate and stacked odds). Six bonus modes are available from the beginning of the game (no unlocking required) and offer diversity in gameplay. Modes include Comical (damage accompanied by a laugh track), Stingy (one aircraft and one special weapon), No Mercy (unerring enemy fire), Slow (slow enemy fire but rate-multiplied), Ancient (bleached out color to eliminate power-up recognition), and Pocket (block-shaped symbols in basic form).",
      url: "https://www.igdb.com/games/gekioh-shooting-king",
    },
  },
  {
    id: 54,
    score: 155.95908498764038,
    document: {
      id: 19428,
      collection: {
        id: 804,
        created_at: 1393769229,
        games: [
          4144, 5491, 5492, 5493, 5494, 10908, 19410, 19412, 19414, 19424,
          19428, 21757, 22594, 23146, 31719, 44703, 46022, 46029,
        ],
        name: "Armored Core",
        slug: "armored-core",
        updated_at: 1665553328,
        url: "https://www.igdb.com/collections/armored-core",
        checksum: "5d09b5c0-cfbf-8084-ffa8-f0018d1d8797",
      },
      cover: {
        id: 117089,
        alpha_channel: false,
        animated: false,
        game: 19428,
        height: 1600,
        image_id: "co2ich",
        url: "https://images.igdb.com/igdb/image/upload/t_1080p/co2ich.jpg",
        width: 1200,
        checksum: "d0bd939e-d061-652d-16d6-b537c5d5e182",
      },
      first_release_date: 881193600,
      genres: [
        {
          id: 5,
          name: "Shooter",
        },
        {
          id: 31,
          name: "Adventure",
        },
      ],
      involved_companies: [
        {
          id: 35860,
          company: {
            id: 1566,
            name: "Agetec",
          },
          created_at: 1464998400,
          developer: false,
          game: 19428,
          porting: false,
          publisher: true,
          supporting: false,
          updated_at: 1464998400,
          checksum: "548a187b-37fa-8b49-7e93-d865e050da90",
        },
        {
          id: 45786,
          company: {
            id: 1012,
            name: "FromSoftware",
          },
          created_at: 1491350400,
          developer: true,
          game: 19428,
          porting: false,
          publisher: false,
          supporting: false,
          updated_at: 1491350400,
          checksum: "1f1878c3-7703-4eee-837d-8bc37ce145ea",
        },
      ],
      name: "Armored Core: Project Phantasma",
      screenshots: [
        {
          id: 350484,
          alpha_channel: false,
          animated: false,
          game: 19428,
          height: 360,
          image_id: "sc7ifo",
          url: "https://images.igdb.com/igdb/image/upload/t_1080p/sc7ifo.jpg",
          width: 480,
          checksum: "308bef5c-d032-06a1-f76b-2f2b3a37319f",
        },
        {
          id: 350485,
          alpha_channel: false,
          animated: false,
          game: 19428,
          height: 360,
          image_id: "sc7ifp",
          url: "https://images.igdb.com/igdb/image/upload/t_1080p/sc7ifp.jpg",
          width: 480,
          checksum: "7554d6c9-0628-0eb6-6e7f-e44c45bb254b",
        },
        {
          id: 350486,
          alpha_channel: false,
          animated: false,
          game: 19428,
          height: 360,
          image_id: "sc7ifq",
          url: "https://images.igdb.com/igdb/image/upload/t_1080p/sc7ifq.jpg",
          width: 480,
          checksum: "6fc76b9e-7863-c71b-63b9-8dc5a5fd1fcb",
        },
      ],
      slug: "armored-core-project-phantasma",
      summary:
        'A Raven operating out of Isaac City receives an unusual request. Not only is the request both vague and cryptic, stating simply: "Infiltrate the underground urban complex, Amber Crown,", but it also bypasses normal channels of communication and is sent directly to the Raven in question, without anyone else seeing the message. No sender name or corporate affiliation is mentioned, but the monetary reward promised is massive. Because of the amount, the mission will obviously be intensely dangerous, but Ravens aren\'t the type to shy away from any challenge. With interest piqued, the Raven climbs into the AC and heads toward Amber Crown.',
      url: "https://www.igdb.com/games/armored-core-project-phantasma",
    },
  },
  {
    id: 141,
    score: 153.81859254837036,
    document: {
      id: 1810,
      alternative_names: [
        {
          id: 54729,
          name: "Bureivu Fensaa Musashiden",
        },
        {
          id: 54730,
          name: "ブレイヴフェンサー 武蔵伝",
        },
      ],
      collection: {
        id: 347,
        created_at: 1352636095,
        games: [1810, 1811],
        name: "Brave Fencer Musashi",
        slug: "brave-fencer-musashi",
        updated_at: 1652300812,
        url: "https://www.igdb.com/collections/brave-fencer-musashi",
        checksum: "dbfc0b92-b868-6873-382f-188d0c90c394",
      },
      cover: {
        id: 154795,
        alpha_channel: false,
        animated: false,
        game: 1810,
        height: 800,
        image_id: "co3bfv",
        url: "https://images.igdb.com/igdb/image/upload/t_1080p/co3bfv.jpg",
        width: 600,
        checksum: "6cbffbd0-3efc-6b77-a3d4-da2608d09fed",
      },
      first_release_date: 900547200,
      genres: [
        {
          id: 12,
          name: "Role-playing (RPG)",
        },
        {
          id: 31,
          name: "Adventure",
        },
      ],
      involved_companies: [
        {
          id: 18343,
          company: {
            id: 250,
            name: "Square",
          },
          created_at: 1413504000,
          developer: true,
          game: 1810,
          porting: false,
          publisher: true,
          supporting: false,
          updated_at: 1413504000,
          checksum: "71ad1db7-6aab-69cc-0ab2-846a0fa81f3f",
        },
        {
          id: 18344,
          company: {
            id: 252,
            name: "Square Electronic Arts",
          },
          created_at: 1413504000,
          developer: false,
          game: 1810,
          porting: false,
          publisher: true,
          supporting: false,
          updated_at: 1413504000,
          checksum: "ec224447-3e01-6b65-e0b0-fc2b300e0c64",
        },
        {
          id: 18345,
          company: {
            id: 26,
            name: "Square Enix",
          },
          created_at: 1413504000,
          developer: false,
          game: 1810,
          porting: false,
          publisher: true,
          supporting: false,
          updated_at: 1413504000,
          checksum: "b78df12c-c820-0fe2-b293-81c191884ff0",
        },
      ],
      name: "Brave Fencer Musashi",
      slug: "brave-fencer-musashi",
      summary:
        "150 years ago, the legendary warrior known as the Brave Fencer Musashi saved the kingdom of Allucaneet from the evil Wizard of Darkness. Now, his spirit is reincarnated in a young, rather short-tempered boy. Fillet, the princess of Allucaneet, summons the reluctant hero to the palace and gives him the powerful sword Fusion, which he needs to defeat the evil Thirstquencher Empire. It soon turns out that the Empire is after another legendary sword, Lumina, so Musashi's first task is to get it before the bad guys do!..\n\nBrave Fencer Musashi is an action game with strong RPG elements. Controlling Musashi, the player explores the pre-rendered backgrounds from third person view (similarly to Final Fantasy VII), visiting towns, talking to NPCs, etc. There is a day/night cycle in the game, which is manifested in the schedules of NPCs and/or monsters, as well as Musashi's fatigue level, which increases if he doesn't sleep enough. Musashi uses the two swords, Fusion and Lumina, to fight his enemies. The two swords have different properties: while Fusion behaves more or less like a traditional melee weapon, Lumina needs to be imbued with various elemental items in order to unleash powerful attacks.",
      total_rating: 76.98654529548409,
      total_rating_count: 7,
      url: "https://www.igdb.com/games/brave-fencer-musashi",
    },
  },
  {
    id: 253,
    score: 153.1623830795288,
    document: {
      id: 2399,
      cover: {
        id: 96626,
        alpha_channel: false,
        animated: false,
        game: 2399,
        height: 1480,
        image_id: "co22k2",
        url: "https://images.igdb.com/igdb/image/upload/t_1080p/co22k2.jpg",
        width: 1110,
        checksum: "374db168-41f0-8999-1b7c-dd6274d71114",
      },
      first_release_date: 867628800,
      genres: [
        {
          id: 13,
          name: "Simulator",
        },
      ],
      involved_companies: [
        {
          id: 5586,
          company: {
            id: 1,
            name: "Electronic Arts",
          },
          created_at: 1372809600,
          developer: false,
          game: 2399,
          porting: false,
          publisher: true,
          supporting: false,
          updated_at: 1372809600,
          checksum: "5aa6ff6c-e11e-e9b2-493b-5969f164ded6",
        },
        {
          id: 5587,
          company: {
            id: 543,
            name: "Rage Software",
          },
          created_at: 1372809600,
          developer: true,
          game: 2399,
          porting: false,
          publisher: false,
          supporting: false,
          updated_at: 1372809600,
          checksum: "6ccc1baf-0b23-2bd3-73d4-37a0280830a0",
        },
      ],
      name: "Darklight Conflict",
      slug: "darklight-conflict",
      summary:
        'Darklight Conflict is a space combat simulator video game developed by Rage Software and published by Electronic Arts in 1997 for PCs running MS-DOS or versions of Microsoft Windows before Windows 2000, and the Sega Saturn and Sony PlayStation game consoles. In this game, you play the part of a contemporary human fighter pilot abducted by the alien Repton species during your aerial battle, and biologically modified to become a starfighter pilot for them in their war against the Evil Ovon race.\n\nIn the game itself, you would usually pilot one of three different starfighters, each with different strengths and weaknesses, along with occasionally piloting a captured enemy ship, or controlling a gun turret on your Mothership (The "War Drum"). The missions are quite varied, ranging from simple combat missions to missions where you need to defend your mothership, destroy an enemy Ovon mothership, clear an asteroid field, or retrieve an object with a tractor beam. Your ship moves between mission areas via "hyperspace portals", passing through a hyper-space environment, resembling that seen in 2001: A Space Odyssey. Often during hyperspace transit, varying streams of energy are encountered - yellow energy replenishing the energy which fuels the ship, while blue energy drains it, reducing the ship\'s effectiveness.\n\nAfter you complete the four campaigns and destroy the Ovon home-world for the Reptons, they reward you by sending their best pilots to kill you in an honorable way (after all, they don\'t need a human in their society and war history). You manage to escape and jump to Earth, where centuries have passed since you were gone. Your ship is greeted by the Earth Defense Fleet, which destroys all Repton ships in hot pursuit.',
      total_rating: 70,
      total_rating_count: 1,
      url: "https://www.igdb.com/games/darklight-conflict",
    },
  },
  {
    id: 10,
    score: 152.0769076347351,
    document: {
      id: 98269,
      alternative_names: [
        {
          id: 54766,
          name: "A-Train - Trains, Power, Money",
        },
      ],
      collection: {
        id: 1335,
        created_at: 1430335800,
        games: [
          9990, 9991, 9992, 9993, 9994, 9995, 9996, 9997, 9998, 9999, 10000,
          10001, 10002, 10003, 10004, 10005, 27693, 41739, 42301, 57587, 69497,
          74698, 98269,
        ],
        name: "A-Train",
        slug: "a-train",
        updated_at: 1661163230,
        url: "https://www.igdb.com/collections/a-train",
        checksum: "620f668e-a0fd-bbac-3764-75b1867b7beb",
      },
      cover: {
        id: 129778,
        alpha_channel: false,
        animated: false,
        game: 98269,
        height: 988,
        image_id: "co2s4y",
        url: "https://images.igdb.com/igdb/image/upload/t_1080p/co2s4y.jpg",
        width: 1000,
        checksum: "2ed1da77-78e0-6eba-e8d9-132d11a65973",
      },
      first_release_date: 820454400,
      genres: [
        {
          id: 13,
          name: "Simulator",
        },
      ],
      involved_companies: [
        {
          id: 118518,
          company: {
            id: 1221,
            name: "Artdink",
          },
          created_at: 1612483200,
          developer: true,
          game: 98269,
          porting: false,
          publisher: false,
          supporting: false,
          updated_at: 1612483200,
          checksum: "31975f7d-4275-eb18-0c02-b74a7a0befb9",
        },
        {
          id: 118519,
          company: {
            id: 22170,
            name: "Maxis Software",
          },
          created_at: 1612483200,
          developer: false,
          game: 98269,
          porting: false,
          publisher: true,
          supporting: false,
          updated_at: 1612483200,
          checksum: "1f28129c-3373-d030-46f7-09b86420ee01",
        },
      ],
      name: "A-Train: Trains, Power, Money",
      slug: "a-train-trains-power-money",
      summary:
        "Although trains are your primary source of income in the beginning of the game, A-Train is not about building trains exclusively. By utilizing the train industry as well as buses and subways, it is up to you to manage an efficient transportation system for passengers and freighting companies. Everything you do must be well thought out because you're out to make a profit. \n \nAs soon as you've earned the adequate funds, you have to start making investments. With your money you can buy and sell all types of land and businesses. If you think you're lucky enough, you may opt to play the stock market. Purchased land can be developed in a variety of ways, such as in the development of offices, apartments, hotels, factories, golf courses, and so on. It is up to you to build the largest financial empire humanly possible. \n \nAs the city develops, new businesses will spring up, such as stadiums, high rise office blocks, and ski resorts. You can also build your own businesses, the success of which will depend on the local population, the presence of competing businesses, and even the changes of the seasons, among other factors.",
      url: "https://www.igdb.com/games/a-train-trains-power-money",
    },
  },
  {
    id: 1085,
    score: 151.3864860534668,
    document: {
      id: 44990,
      alternative_names: [
        {
          id: 60712,
          name: "Top Gun PSX",
        },
        {
          id: 60713,
          name: "Top Gun PS1",
        },
      ],
      collection: {
        id: 2435,
        created_at: 1474400267,
        games: [
          9236, 18021, 20129, 22910, 22911, 22912, 22913, 22914, 22915, 44990,
          49209, 66496, 73092, 146784,
        ],
        name: "Top Gun",
        slug: "top-gun",
        updated_at: 1664431421,
        url: "https://www.igdb.com/collections/top-gun",
        checksum: "e6bf58ad-4aa8-33f2-fcea-4c3222fce642",
      },
      cover: {
        id: 139178,
        alpha_channel: true,
        animated: false,
        game: 44990,
        height: 1591,
        image_id: "co2ze2",
        url: "https://images.igdb.com/igdb/image/upload/t_1080p/co2ze2.jpg",
        width: 1193,
        checksum: "c325361b-f068-32db-ddaa-b0e6062a79d9",
      },
      first_release_date: 834537600,
      genres: [
        {
          id: 5,
          name: "Shooter",
        },
        {
          id: 13,
          name: "Simulator",
        },
      ],
      involved_companies: [
        {
          id: 127970,
          company: {
            id: 1044,
            name: "Spectrum HoloByte, Inc.",
          },
          created_at: 1620288887,
          developer: true,
          game: 44990,
          porting: false,
          publisher: true,
          supporting: false,
          updated_at: 1620289539,
          checksum: "4e72c89f-5c4b-037a-08eb-69ccf44886ff",
        },
      ],
      name: "Top Gun: Fire at Will!",
      screenshots: [
        {
          id: 441258,
          alpha_channel: false,
          animated: false,
          game: 44990,
          height: 240,
          image_id: "sc9gh6",
          url: "https://images.igdb.com/igdb/image/upload/t_1080p/sc9gh6.jpg",
          width: 320,
          checksum: "51cbc940-e71c-8211-1b77-b4007b31f370",
        },
        {
          id: 441259,
          alpha_channel: false,
          animated: false,
          game: 44990,
          height: 240,
          image_id: "sc9gh7",
          url: "https://images.igdb.com/igdb/image/upload/t_1080p/sc9gh7.jpg",
          width: 320,
          checksum: "ed6e3ad9-d0c0-a694-3571-ef90635950bc",
        },
        {
          id: 441260,
          alpha_channel: false,
          animated: false,
          game: 44990,
          height: 240,
          image_id: "sc9gh8",
          url: "https://images.igdb.com/igdb/image/upload/t_1080p/sc9gh8.jpg",
          width: 320,
          checksum: "67d1b47a-64da-28e0-8eb6-162c18bbf507",
        },
        {
          id: 441261,
          alpha_channel: false,
          animated: false,
          game: 44990,
          height: 480,
          image_id: "sc9gh9",
          url: "https://images.igdb.com/igdb/image/upload/t_1080p/sc9gh9.jpg",
          width: 640,
          checksum: "ebf832de-1608-847d-eef9-d4710f9b8452",
        },
        {
          id: 441262,
          alpha_channel: false,
          animated: false,
          game: 44990,
          height: 240,
          image_id: "sc9gha",
          url: "https://images.igdb.com/igdb/image/upload/t_1080p/sc9gha.jpg",
          width: 320,
          checksum: "5b9e92cb-1cd8-4a81-e212-08c8fe140805",
        },
        {
          id: 441263,
          alpha_channel: false,
          animated: false,
          game: 44990,
          height: 240,
          image_id: "sc9ghb",
          url: "https://images.igdb.com/igdb/image/upload/t_1080p/sc9ghb.jpg",
          width: 320,
          checksum: "c8f2644f-a270-e81f-03ac-a55a3cd86ddf",
        },
        {
          id: 441264,
          alpha_channel: false,
          animated: false,
          game: 44990,
          height: 240,
          image_id: "sc9ghc",
          url: "https://images.igdb.com/igdb/image/upload/t_1080p/sc9ghc.jpg",
          width: 320,
          checksum: "791b4782-d6d2-5be8-684c-19f811738e81",
        },
        {
          id: 441265,
          alpha_channel: false,
          animated: false,
          game: 44990,
          height: 240,
          image_id: "sc9ghd",
          url: "https://images.igdb.com/igdb/image/upload/t_1080p/sc9ghd.jpg",
          width: 320,
          checksum: "12faf21b-8968-0377-80d3-3d1f5572ac6a",
        },
        {
          id: 441266,
          alpha_channel: false,
          animated: false,
          game: 44990,
          height: 240,
          image_id: "sc9ghe",
          url: "https://images.igdb.com/igdb/image/upload/t_1080p/sc9ghe.jpg",
          width: 320,
          checksum: "f893cdc5-01ae-0803-fb11-564a4bbd252c",
        },
      ],
      slug: "top-gun-fire-at-will--1",
      summary:
        "The PlayStation version differs greatly from the PC versions, emphasizing action over simulation; in particular, take-offs and landings were cut, and the player begins each mission with enemies near at hand, rather than having to hunt them down.\n\nPlayers will be manning the F-14 fighter plane. Not only does this baby come with all the necessary tools and equipment needed for survival (radar, warning lights, altitude meters), it comes with a variety of missiles; there are standard air-to-air missiles, the air-to-ground AGMs, U238s made from depleted uranium, a disastrous Nuke, and the multiple target MIRV. It also comes with some defensive tools such as chaffs and flares that trick enemy radar.\n\nDon't worry, you're not going in the air alone! Merlin will act as your Radar Intercept Officer; loosely translated, he's the guy that sits behind you and watches out for enemy target locks. Additionally, the sweetly calm Raven and your arch rival Stinger will assist Maverick as his wingmen. When you get in a sticky situation, count on these guys to help you out!",
      url: "https://www.igdb.com/games/top-gun-fire-at-will--1",
      videos: [
        {
          id: 48974,
          game: 44990,
          name: "Gameplay Video",
          video_id: "SAI0f54J0ZY",
          checksum: "639a385f-74b7-ba04-c691-6654c75795d7",
        },
      ],
    },
  },
  {
    id: 809,
    score: 150.24224281311035,
    document: {
      id: 20296,
      cover: {
        id: 161740,
        alpha_channel: false,
        animated: false,
        game: 20296,
        height: 800,
        image_id: "co3gss",
        url: "https://images.igdb.com/igdb/image/upload/t_1080p/co3gss.jpg",
        width: 600,
        checksum: "8ee377c3-4463-6e67-f5e4-f010c29a7d28",
      },
      first_release_date: 844128000,
      genres: [
        {
          id: 5,
          name: "Shooter",
        },
      ],
      name: "Project: Horned Owl",
      screenshots: [
        {
          id: 306920,
          alpha_channel: false,
          animated: false,
          game: 20296,
          height: 168,
          image_id: "sc6ktk",
          url: "https://images.igdb.com/igdb/image/upload/t_1080p/sc6ktk.jpg",
          width: 299,
          checksum: "766fefdc-39ba-067f-25f8-8a1de533fbb5",
        },
        {
          id: 306921,
          alpha_channel: false,
          animated: false,
          game: 20296,
          height: 480,
          image_id: "sc6ktl",
          url: "https://images.igdb.com/igdb/image/upload/t_1080p/sc6ktl.jpg",
          width: 640,
          checksum: "736b6c54-1e78-356f-a48b-a342f11aa416",
        },
        {
          id: 306922,
          alpha_channel: false,
          animated: false,
          game: 20296,
          height: 720,
          image_id: "sc6ktm",
          url: "https://images.igdb.com/igdb/image/upload/t_1080p/sc6ktm.jpg",
          width: 1280,
          checksum: "1fb552c8-f30c-17a1-5860-39665393402d",
        },
      ],
      slug: "project-horned-owl",
      summary:
        "An invasion of mechanized terrorists turns your city into an urban battleground!\n\nTime: the future- Metro City is under attack from legions of robots directed by a twisted dictator. Your squad of mech-suited cops hits the ground, transformed into deadly defense unit. Your city is buckling, street by street - can you stop a total mech takeover?\n\n-A non-stop action shooter exclusively for the PlayStation game console.\n-Two player co-op mode and KONAMI ENFORCER Gun support double the destruction!\n-Interactive backgrounds allow you to blast cars, obliterate walls and annihilate mech suits on factory conveyors. Watch out-innocent civilians are everywhere!\n-Incredible Japanese anime sequences connect battle scenes into an all out urban war!\n-Rapid fire combat packed with futuristic war machines including cybercops, armored mechs with automatic weapons, tanks, missiles, bombs, energy scans and high-tech Heads-Up-displays.",
      total_rating: 60,
      total_rating_count: 1,
      url: "https://www.igdb.com/games/project-horned-owl",
    },
  },
  {
    id: 1126,
    score: 149.82908630371094,
    document: {
      id: 3332,
      alternative_names: [
        {
          id: 16522,
          name: "V8",
        },
        {
          id: 43281,
          name: "V8",
        },
      ],
      collection: {
        id: 4213,
        created_at: 1509925073,
        games: [3332, 3333, 23035, 75423],
        name: "Vigilante 8",
        slug: "vigilante-8",
        updated_at: 1667993381,
        url: "https://www.igdb.com/collections/vigilante-8",
        checksum: "4110eb05-3f4c-c8dc-873d-1d4e234effb7",
      },
      cover: {
        id: 154515,
        alpha_channel: false,
        animated: false,
        game: 3332,
        height: 800,
        image_id: "co3b83",
        url: "https://images.igdb.com/igdb/image/upload/t_1080p/co3b83.jpg",
        width: 600,
        checksum: "c132a085-8be7-e0ac-0004-ead2dc57f66a",
      },
      first_release_date: 896659200,
      genres: [
        {
          id: 4,
          name: "Fighting",
        },
        {
          id: 5,
          name: "Shooter",
        },
      ],
      involved_companies: [
        {
          id: 37204,
          company: {
            id: 66,
            name: "Activision",
          },
          created_at: 1467331200,
          developer: false,
          game: 3332,
          porting: false,
          publisher: true,
          supporting: false,
          updated_at: 1467331200,
          checksum: "7f1e8bc2-6e8e-b467-bbcb-00227948b8cc",
        },
        {
          id: 37205,
          company: {
            id: 65,
            name: "Luxoflux",
          },
          created_at: 1467331200,
          developer: true,
          game: 3332,
          porting: false,
          publisher: false,
          supporting: false,
          updated_at: 1467331200,
          checksum: "a011dd08-2ef0-3209-8627-1ae41fb17eef",
        },
      ],
      name: "Vigilante 8",
      screenshots: [
        {
          id: 6980,
          game: 3332,
          height: 194,
          image_id: "cbeewycoqvvuprkhoxba",
          url: "https://images.igdb.com/igdb/image/upload/t_1080p/cbeewycoqvvuprkhoxba.jpg",
          width: 259,
          checksum: "0a13596f-43c2-8dc0-00f8-fb3933c08a36",
        },
        {
          id: 6981,
          game: 3332,
          height: 194,
          image_id: "tm6hecc50ovcxisxrx5k",
          url: "https://images.igdb.com/igdb/image/upload/t_1080p/tm6hecc50ovcxisxrx5k.jpg",
          width: 259,
          checksum: "3567f934-2e3d-c5a1-5e94-4acae15587a4",
        },
        {
          id: 6982,
          game: 3332,
          height: 194,
          image_id: "j1htivdocy6rmksr9yo0",
          url: "https://images.igdb.com/igdb/image/upload/t_1080p/j1htivdocy6rmksr9yo0.jpg",
          width: 259,
          checksum: "d57e4135-19fa-a0d3-f3c2-e5681f028082",
        },
      ],
      slug: "vigilante-8",
      summary:
        "The game's storyline is built around an alternate history, in which there was a worldwide oil crisis in the 1970s and the U.S. was on the verge of an economic breakdown. Strikes, riots and crime were rampant, and all available law enforcement were brought to the cities leaving the outlands vulnerable. A foreign multinational oil consortium, Oil Monopoly Alliance Regime (OMAR), was determined to monopolize the world oil trade. The U.S. was the last country that stood in their way and they were prepared to go to any length to bring the U.S. to its knees.\nOMAR hired Sid Burn, a professional terrorist, to push the U.S. economy over the edge. Sid began to organize his troops in the remote areas of the southwest. Calling themselves the \"Coyotes,\" they began to target oil refineries, commercial installations and other vital industry throughout the region. With the law enforcement in the cities, some desperate civilians began to take the law into their own hands. Led by a trucker named Convoy and referred to simply as the \"Vigilantes,\" this oddball group soon became a major hindrance to Sid.\nMeanwhile, the U.S. government, feeling more vulnerable than ever, was intensifying its research and development of a new military arsenal. The most advanced weaponry, rumored to be based on UFO technology, was located at Site-4, a secret facility at Papoose Lake. This information was not lost on Sid, and the Coyotes ambushed the facility. However the Vigilantes unexpectedly appeared to stop them and as a result, both parties found themselves in possession of the world's most advanced weaponry.\nWhat followed were no ordinary skirmishes. Auto clashes ensued all over the land, from Colorado's Rockies to California's farmlands, only to culminate in a battle like no other. To this day the events which took place are only a matter of speculation.",
      total_rating: 54.7412497867385,
      total_rating_count: 44,
      url: "https://www.igdb.com/games/vigilante-8",
    },
  },
  {
    id: 1151,
    score: 149.33635711669922,
    document: {
      id: 51297,
      cover: {
        id: 129409,
        alpha_channel: false,
        animated: false,
        game: 51297,
        height: 800,
        image_id: "co2rup",
        url: "https://images.igdb.com/igdb/image/upload/t_1080p/co2rup.jpg",
        width: 600,
        checksum: "d759c7ee-1f14-218f-c956-f2aea4ce585b",
      },
      first_release_date: 923702400,
      genres: [
        {
          id: 11,
          name: "Real Time Strategy (RTS)",
        },
        {
          id: 15,
          name: "Strategy",
        },
      ],
      involved_companies: [
        {
          id: 124675,
          company: {
            id: 33362,
            name: "Warzone 2100 Project",
          },
          created_at: 1618783801,
          developer: true,
          game: 51297,
          porting: true,
          publisher: true,
          supporting: true,
          updated_at: 1618835833,
          checksum: "838e3233-85d0-63d4-03bb-273f9b5123f3",
        },
      ],
      name: "Warzone 2100",
      screenshots: [
        {
          id: 111817,
          game: 51297,
          height: 750,
          image_id: "zbtdgir0t9hlocbobcyj",
          url: "https://images.igdb.com/igdb/image/upload/t_1080p/zbtdgir0t9hlocbobcyj.jpg",
          width: 1000,
          checksum: "ffd3cad4-f1fc-cf49-7270-879a15e9e93c",
        },
        {
          id: 111818,
          game: 51297,
          height: 1024,
          image_id: "arpklvxwerab8fel0miz",
          url: "https://images.igdb.com/igdb/image/upload/t_1080p/arpklvxwerab8fel0miz.jpg",
          width: 1280,
          checksum: "a3bea2a5-f717-8a67-0b2a-6f47809bd653",
        },
        {
          id: 111819,
          game: 51297,
          height: 768,
          image_id: "kchdt4qd7gxlzunbuzhz",
          url: "https://images.igdb.com/igdb/image/upload/t_1080p/kchdt4qd7gxlzunbuzhz.jpg",
          width: 1024,
          checksum: "0cba0059-cdec-e8e5-d8d1-1ddbe84dc219",
        },
        {
          id: 111820,
          game: 51297,
          height: 1024,
          image_id: "pqbswskqbsguul1gajph",
          url: "https://images.igdb.com/igdb/image/upload/t_1080p/pqbswskqbsguul1gajph.jpg",
          width: 1280,
          checksum: "535bd2fd-b057-ac06-437c-b7508db6969a",
        },
      ],
      slug: "warzone-2100",
      summary:
        'In the late 21st century, NASDA (the North American Strategic Defense Agency) developed and deployed a massive missile defense system, including a network of nuclear-equipped satellites and ground-based launch sites. However, during a routine maintenance check, something went terribly wrong...\n\nWhile most of the survivors form scavenger bands to survive, one group of people, who refer to themselves as "The Project", seeks to rebuild civilization using pre-war technology.\n\nWarzone 2100 is a real-time strategy game, originally developed by Pumpkin Studios and published by Eidos Interactive, now developed by the Warzone 2100 Project. Compared to other real-time strategy games, it has a greater focus on artillery, radar, and counter-battery technologies, more frequent in-game cinematic updates as game play progresses, a massive research tree, as well as a vehicle design system.\n\nOutside of the story, Warzone 2100 only has a single faction. This limits some of the variety that can be expected from real-time strategy games, although the single faction is very complex. Essentially, Warzone 2100 plays much like Earth 2150 with 3D units and terrain, customizable vehicles, a lack of traditional infantry, use of "research" to acquire new technologies, and the differentiation of vehicles types.',
      url: "https://www.igdb.com/games/warzone-2100",
      videos: [
        {
          id: 29365,
          game: 51297,
          name: "Trailer",
          video_id: "hHR7ik566Kg",
          checksum: "13c915ab-a1cb-9d09-c9fb-5dfe8226841a",
        },
        {
          id: 48116,
          game: 51297,
          name: "Teaser",
          video_id: "27VMeYord8g",
          checksum: "da4778e9-64d5-88e3-01a0-cb91365dfdea",
        },
      ],
    },
  },
  {
    id: 453,
    score: 149.02538681030273,
    document: {
      id: 45223,
      cover: {
        id: 205715,
        alpha_channel: true,
        animated: false,
        game: 45223,
        height: 800,
        image_id: "co4eqb",
        url: "https://images.igdb.com/igdb/image/upload/t_1080p/co4eqb.jpg",
        width: 600,
        checksum: "f5edf399-9827-f30e-8f26-36b079b602bd",
      },
      first_release_date: 1011484800,
      genres: [
        {
          id: 12,
          name: "Role-playing (RPG)",
        },
        {
          id: 15,
          name: "Strategy",
        },
      ],
      name: "Hoshigami: Ruining Blue Earth",
      slug: "hoshigami-ruining-blue-earth",
      summary:
        "Utilizing a host of new gameplay elements, Hoshigami: Ruining Blue Earth expands upon the formula made popular by the cult classic Final Fantasy Tactics. The continent of Mardias serves as the game's primary world, and is divided into three kingdoms: Nightweld, the Valaimian Empire and Gerauld. The story begins as Valaimian troops advance into Nightweld, a peace-loving kingdom. Lacking the military might to repel the invaders from multiple fronts, Fazz - a mercenary and the game's protagonist - is hired to defend the Tower of Wind. Needless to say, this is just the beginning of a dire and perilous journey for the unwitting Fazz.\n\nAs you and your party trek across the world map, you'll take part in various battles. Ready-for-Action Points (RAP) determine which, as well as the number of actions that can be performed by a particular character. The more actions performed (and thus, more RAPs expended) during a turn, the longer you'll have to wait for your next chance to act. When attacking, an interactive gauge appears that does damage based upon where the slider is stopped. Stopping it at the very end will result in greater damage dealt to the enemy. Wait too long however and the slider will return to the beginning.",
      url: "https://www.igdb.com/games/hoshigami-ruining-blue-earth",
    },
  },
  {
    id: 749,
    score: 148.9797649383545,
    document: {
      id: 999,
      alternative_names: [
        {
          id: 30020,
          name: "Oddworld : L'Odyssée d'Abe",
        },
        {
          id: 68293,
          name: "Abe's Odyssey",
        },
        {
          id: 68295,
          name: "Oddworld: Abe's Oddysee HD",
        },
        {
          id: 94599,
          name: "Abe a GoGo",
        },
        {
          id: 94600,
          name: "SoulStorm",
        },
      ],
      collection: {
        id: 223,
        created_at: 1322574238,
        games: [
          999, 1000, 1001, 1002, 5552, 18357, 21070, 49015, 49865, 51329, 65861,
          66007, 118466, 121444, 134025, 146008, 146118, 178211,
        ],
        name: "Oddworld",
        slug: "oddworld",
        updated_at: 1668482507,
        url: "https://www.igdb.com/collections/oddworld",
        checksum: "4a88666f-5c41-9c5c-618b-823e4ead2712",
      },
      cover: {
        id: 91026,
        alpha_channel: false,
        animated: false,
        game: 999,
        height: 1000,
        image_id: "co1y8i",
        url: "https://images.igdb.com/igdb/image/upload/t_1080p/co1y8i.jpg",
        width: 750,
        checksum: "1ecae903-116f-f07f-eb30-647171645e18",
      },
      first_release_date: 874540800,
      genres: [
        {
          id: 8,
          name: "Platform",
        },
        {
          id: 9,
          name: "Puzzle",
        },
        {
          id: 31,
          name: "Adventure",
        },
      ],
      involved_companies: [
        {
          id: 178220,
          company: {
            id: 727,
            name: "Oddworld Inhabitants",
          },
          created_at: 1657315968,
          developer: true,
          game: 999,
          porting: false,
          publisher: false,
          supporting: false,
          updated_at: 1657437938,
          checksum: "9e763c35-051d-588c-b83c-87e07dd347c1",
        },
        {
          id: 178224,
          company: {
            id: 205,
            name: "GT Interactive",
          },
          created_at: 1657316262,
          developer: false,
          game: 999,
          porting: false,
          publisher: true,
          supporting: false,
          updated_at: 1657437938,
          checksum: "f0b36c34-4f8f-0e5e-7d29-92b79cc925a9",
        },
        {
          id: 178225,
          company: {
            id: 727,
            name: "Oddworld Inhabitants",
          },
          created_at: 1657316262,
          developer: false,
          game: 999,
          porting: false,
          publisher: true,
          supporting: false,
          updated_at: 1657437938,
          checksum: "bfe7dcb6-f900-5664-423e-3bf4d557ee30",
        },
        {
          id: 178226,
          company: {
            id: 311,
            name: "Digital Dialect",
          },
          created_at: 1657316263,
          developer: false,
          game: 999,
          porting: true,
          publisher: false,
          supporting: false,
          updated_at: 1657437938,
          checksum: "6cbcf0b3-399f-b5ef-80c8-e18aa1f0f117",
        },
      ],
      name: "Oddworld: Abe's Oddysee",
      screenshots: [
        {
          id: 552137,
          alpha_channel: false,
          animated: false,
          game: 999,
          height: 480,
          image_id: "scbu15",
          url: "https://images.igdb.com/igdb/image/upload/t_1080p/scbu15.jpg",
          width: 640,
          checksum: "a745c1b6-0704-20c3-2269-921fb0a3ddaf",
        },
        {
          id: 552138,
          alpha_channel: false,
          animated: false,
          game: 999,
          height: 480,
          image_id: "scbu16",
          url: "https://images.igdb.com/igdb/image/upload/t_1080p/scbu16.jpg",
          width: 640,
          checksum: "f89a249b-afae-2f14-763b-602543b10587",
        },
        {
          id: 552139,
          alpha_channel: false,
          animated: false,
          game: 999,
          height: 480,
          image_id: "scbu17",
          url: "https://images.igdb.com/igdb/image/upload/t_1080p/scbu17.jpg",
          width: 640,
          checksum: "f66e1a79-715f-0cf0-c9ed-d79f1ff29f76",
        },
        {
          id: 552140,
          alpha_channel: false,
          animated: false,
          game: 999,
          height: 480,
          image_id: "scbu18",
          url: "https://images.igdb.com/igdb/image/upload/t_1080p/scbu18.jpg",
          width: 640,
          checksum: "20f7fc40-9f80-6bdf-ec74-dfd5a0516009",
        },
        {
          id: 552141,
          alpha_channel: false,
          animated: false,
          game: 999,
          height: 480,
          image_id: "scbu19",
          url: "https://images.igdb.com/igdb/image/upload/t_1080p/scbu19.jpg",
          width: 640,
          checksum: "0cf1d50a-0329-5d33-deb8-36cd7262903d",
        },
        {
          id: 552142,
          alpha_channel: false,
          animated: false,
          game: 999,
          height: 480,
          image_id: "scbu1a",
          url: "https://images.igdb.com/igdb/image/upload/t_1080p/scbu1a.jpg",
          width: 640,
          checksum: "887b9ca8-ad7a-15d8-e862-928495a57b24",
        },
      ],
      slug: "oddworld-abe-s-oddysee",
      storyline:
        "Abe is a Mudokon, a member of a once prosperous race which has now been enslaved by the Glukkons, forced to work in their huge corporations. The food factories have found a new type of meat, delicious to all the inhabitants, though no one knows the recipe. Following his stomach, Abe eavesdrops on the corporate leaders' conversation, and makes the most frightening and disgusting discovery: his own race is that secret delicious food. Alas, Abe has been spotted, and the guards are marching towards him. He must escape, but he can't leave his friends to the mercy of the Glukkons and their henchmen. He must rescue as many as he can, and tell the world the truth about what he has found out.",
      summary:
        "Oddworld: Abe's Oddysee is the first game set in the fictional Oddworld universe. It is a platformer with puzzle-solving elements, focusing on the portrayal of a weak, underpowered character in a grim and hostile world, who has to rely on his cunning to outwit enemies and overcome hazards. The game has pre-rendered background graphics and uses CG movies of similar style to advance the story between the levels.\n\nThe main character Abe is almost completely helpless: he cannot use weapons and is usually instantly killed by his brutal enemies if he confronts them directly. For this reason, most of the game involves careful exploration, timed movement, sneaking, and outsmarting the foes through various means: throwing stones to confuse them, luring them into traps, etc. Abe can run, jump, climb, tiptoe, crouch, and roll; in most areas these actions are essential to his survival. A few stages involve Abe riding a large animal known as Elum.\n\nAbe's only special power is chanting, which he can use to stun certain enemies for a while or possess them. When Abe possess an enemy he gains his abilities: for example, possessing the body or a ferocious Slig allows the player to shoot from his machine gun, communicate with other creatures of his kind, and even commit suicide, clearing the way for Abe.",
      total_rating: 91.1916998914227,
      total_rating_count: 173,
      url: "https://www.igdb.com/games/oddworld-abe-s-oddysee",
      videos: [
        {
          id: 4689,
          game: 999,
          name: "Trailer",
          video_id: "jWCrg3jGCk8",
          checksum: "d4f17aeb-54a6-ab06-45b7-c3e60d329ad5",
        },
        {
          id: 71610,
          game: 999,
          name: "Game Intro",
          video_id: "bLT-hCj8bTA",
          checksum: "5e9759a6-be1d-c451-98d9-aba21c379a80",
        },
      ],
    },
  },
  {
    id: 251,
    score: 148.92680263519287,
    document: {
      id: 45226,
      cover: {
        id: 205696,
        alpha_channel: true,
        animated: false,
        game: 45226,
        height: 800,
        image_id: "co4eps",
        url: "https://images.igdb.com/igdb/image/upload/t_1080p/co4eps.jpg",
        width: 600,
        checksum: "507c14fc-a290-fd69-7651-9b9083765db5",
      },
      first_release_date: 971481600,
      genres: [
        {
          id: 5,
          name: "Shooter",
        },
      ],
      involved_companies: [
        {
          id: 190383,
          company: {
            id: 22453,
            name: "THQ Inc.",
          },
          created_at: 1665292155,
          developer: false,
          game: 45226,
          porting: false,
          publisher: true,
          supporting: false,
          updated_at: 1665334134,
          checksum: "7d1f1a9a-2195-9c67-7248-156c29741d9b",
        },
        {
          id: 190384,
          company: {
            id: 319,
            name: "n-Space",
          },
          created_at: 1665292155,
          developer: true,
          game: 45226,
          porting: false,
          publisher: false,
          supporting: false,
          updated_at: 1665334134,
          checksum: "92dbab9d-69b7-9446-5832-264539437404",
        },
      ],
      name: "Danger Girl",
      screenshots: [
        {
          id: 900236,
          alpha_channel: false,
          animated: false,
          game: 45226,
          height: 480,
          image_id: "scjamk",
          url: "https://images.igdb.com/igdb/image/upload/t_1080p/scjamk.jpg",
          width: 640,
          checksum: "1335f92b-976e-1c9c-ce36-f75eea0b0fc0",
        },
        {
          id: 900237,
          alpha_channel: false,
          animated: false,
          game: 45226,
          height: 480,
          image_id: "scjaml",
          url: "https://images.igdb.com/igdb/image/upload/t_1080p/scjaml.jpg",
          width: 640,
          checksum: "ef6ff090-5f9f-87ba-44ca-d04d1df82fe6",
        },
        {
          id: 900238,
          alpha_channel: false,
          animated: false,
          game: 45226,
          height: 480,
          image_id: "scjamm",
          url: "https://images.igdb.com/igdb/image/upload/t_1080p/scjamm.jpg",
          width: 640,
          checksum: "2fffa535-02d2-b3ca-d6d8-c29e9abbf9bc",
        },
        {
          id: 900239,
          alpha_channel: false,
          animated: false,
          game: 45226,
          height: 480,
          image_id: "scjamn",
          url: "https://images.igdb.com/igdb/image/upload/t_1080p/scjamn.jpg",
          width: 640,
          checksum: "3748dfcd-d9c1-01a4-7e48-082ba7c8bc5e",
        },
        {
          id: 900240,
          alpha_channel: false,
          animated: false,
          game: 45226,
          height: 480,
          image_id: "scjamo",
          url: "https://images.igdb.com/igdb/image/upload/t_1080p/scjamo.jpg",
          width: 640,
          checksum: "299379e6-bd76-53ae-e4f9-eb706cdceaa6",
        },
        {
          id: 900241,
          alpha_channel: false,
          animated: false,
          game: 45226,
          height: 480,
          image_id: "scjamp",
          url: "https://images.igdb.com/igdb/image/upload/t_1080p/scjamp.jpg",
          width: 640,
          checksum: "f1214f25-ce8c-dba7-c59a-a8d27840e572",
        },
        {
          id: 900242,
          alpha_channel: false,
          animated: false,
          game: 45226,
          height: 480,
          image_id: "scjamq",
          url: "https://images.igdb.com/igdb/image/upload/t_1080p/scjamq.jpg",
          width: 640,
          checksum: "36e6b0ce-0a89-f4f0-85f1-5ffd1a4b4432",
        },
        {
          id: 900243,
          alpha_channel: false,
          animated: false,
          game: 45226,
          height: 480,
          image_id: "scjamr",
          url: "https://images.igdb.com/igdb/image/upload/t_1080p/scjamr.jpg",
          width: 640,
          checksum: "3f223f0d-18d9-fe53-2eff-65096e09e1a8",
        },
        {
          id: 900244,
          alpha_channel: false,
          animated: false,
          game: 45226,
          height: 480,
          image_id: "scjams",
          url: "https://images.igdb.com/igdb/image/upload/t_1080p/scjams.jpg",
          width: 640,
          checksum: "0715670d-a867-04f3-4b8d-4df2e6be70aa",
        },
        {
          id: 900245,
          alpha_channel: false,
          animated: false,
          game: 45226,
          height: 480,
          image_id: "scjamt",
          url: "https://images.igdb.com/igdb/image/upload/t_1080p/scjamt.jpg",
          width: 640,
          checksum: "78f3a68b-df66-a273-7dfb-95171521c337",
        },
        {
          id: 900246,
          alpha_channel: false,
          animated: false,
          game: 45226,
          height: 480,
          image_id: "scjamu",
          url: "https://images.igdb.com/igdb/image/upload/t_1080p/scjamu.jpg",
          width: 640,
          checksum: "2b5ecfae-8a70-b097-121d-76160c2e4cac",
        },
        {
          id: 900247,
          alpha_channel: false,
          animated: false,
          game: 45226,
          height: 480,
          image_id: "scjamv",
          url: "https://images.igdb.com/igdb/image/upload/t_1080p/scjamv.jpg",
          width: 640,
          checksum: "f94fbc14-9cae-3d56-8e45-8ea92620f53c",
        },
        {
          id: 900248,
          alpha_channel: false,
          animated: false,
          game: 45226,
          height: 480,
          image_id: "scjamw",
          url: "https://images.igdb.com/igdb/image/upload/t_1080p/scjamw.jpg",
          width: 640,
          checksum: "03b7d0fd-b182-ba71-6082-f108922d64dc",
        },
        {
          id: 900249,
          alpha_channel: false,
          animated: false,
          game: 45226,
          height: 480,
          image_id: "scjamx",
          url: "https://images.igdb.com/igdb/image/upload/t_1080p/scjamx.jpg",
          width: 640,
          checksum: "3c2ec7e9-d072-9163-59ca-15fba59439a7",
        },
        {
          id: 900250,
          alpha_channel: false,
          animated: false,
          game: 45226,
          height: 480,
          image_id: "scjamy",
          url: "https://images.igdb.com/igdb/image/upload/t_1080p/scjamy.jpg",
          width: 640,
          checksum: "1f19ea7c-adfc-3c58-6c9f-921c4137762c",
        },
        {
          id: 900251,
          alpha_channel: false,
          animated: false,
          game: 45226,
          height: 480,
          image_id: "scjamz",
          url: "https://images.igdb.com/igdb/image/upload/t_1080p/scjamz.jpg",
          width: 640,
          checksum: "092261ad-3507-f249-7b64-46f30e83ed3a",
        },
      ],
      slug: "danger-girl",
      summary:
        'Danger Never Looked So Good!\n\n3rd person action-adventure has never been sexier with DANGER GIRL, the only videogame based on on the best-selling comic book series by J. Scott Campbell and Andy Hartnell.\n\nDare to take control of 3 beautiful yet leathal Danger Girls in an espionage-themed thrill-ride deemed to dangerous for any man to handle!\n\n* "I love to unleash my bullwhip, sniper rifle, and grenades on hammer goons!"\n* "Check out our loading screens, featuring original artwork by our creators!"\n* "Help me use my high-tech spy gadgets including infra-red goggles, bomb decoders and more..."\n\nCOLLECTORS ITEM!\nManual features exclusive character sketches, bios and artwork from the creators!',
      url: "https://www.igdb.com/games/danger-girl",
    },
  },
];
